name: py3
dependencies:
  - python=3.9.16
  - pip=23.2.1
  - pip:
      - zipp==3.15.0
      - urllib3<2.0
      - torch>=2.0.0
      - torchaudio>=0.13.0
      - torchvision>=0.13.0
      - tensorflow==2.11.0
      - tensorflow-datasets==4.8.2
      - tensorflow-text==2.11.0
      - matplotlib==3.5.2
      - wandb==0.13.10
      - protobuf==3.19.6
      - numpy==1.26.1